package handlers

import (
	"errors"
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/google/uuid"
	"github.com/BitaceS/talepanel/api/internal/middleware"
	"github.com/BitaceS/talepanel/api/internal/models"
	"github.com/BitaceS/talepanel/api/internal/services"
	"go.uber.org/zap"
)

type WorldHandler struct {
	worldSvc  *services.WorldService
	serverSvc *services.ServerService
	log       *zap.Logger
}

func NewWorldHandler(worldSvc *services.WorldService, serverSvc *services.ServerService, log *zap.Logger) *WorldHandler {
	return &WorldHandler{worldSvc: worldSvc, serverSvc: serverSvc, log: log}
}

// DaemonWorldReport handles POST /servers/:id/daemon/worlds (DaemonNodeAuth).
// The daemon's world scanner reports the worlds present under universe/worlds
// plus the active world from config.json; we upsert them.
func (h *WorldHandler) DaemonWorldReport(c *gin.Context) {
	serverID, ok := parseUUID(c, "id")
	if !ok {
		return
	}

	nodeIDStr, ok := middleware.GetDaemonNodeID(c)
	if !ok {
		c.JSON(http.StatusUnauthorized, gin.H{"error": "node authentication required"})
		return
	}
	nodeID, err := uuid.Parse(nodeIDStr)
	if err != nil {
		c.JSON(http.StatusUnauthorized, gin.H{"error": "invalid node identity"})
		return
	}
	owns, err := h.serverSvc.ServerBelongsToNode(c.Request.Context(), serverID, nodeID)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "ownership check failed"})
		return
	}
	if !owns {
		c.JSON(http.StatusForbidden, gin.H{"error": "server not hosted on this node"})
		return
	}

	var req struct {
		Worlds      []services.ScannedWorld `json:"worlds"`
		ActiveWorld string                  `json:"active_world"`
	}
	if err := c.ShouldBindJSON(&req); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	if err := h.worldSvc.SyncWorlds(c.Request.Context(), serverID, req.Worlds, req.ActiveWorld); err != nil {
		h.log.Warn("failed to sync worlds", zap.String("server_id", serverID.String()), zap.Error(err))
		c.JSON(http.StatusInternalServerError, gin.H{"error": "could not sync worlds"})
		return
	}
	c.Status(http.StatusNoContent)
}

func (h *WorldHandler) ListWorlds(c *gin.Context) {
	serverID, ok := parseUUID(c, "id")
	if !ok {
		return
	}
	worlds, err := h.worldSvc.ListWorlds(c.Request.Context(), serverID)
	if err != nil {
		h.log.Error("failed to list worlds", zap.Error(err))
		c.JSON(http.StatusInternalServerError, gin.H{"error": "could not list worlds"})
		return
	}
	if worlds == nil {
		worlds = []*models.World{}
	}
	c.JSON(http.StatusOK, gin.H{"worlds": worlds})
}

// CreateWorld handles POST /servers/:id/worlds and always returns 501.
//
// It used to insert a row into `worlds` and return 201 — a world that existed
// only in the panel's database. Nothing was created on the node, the server
// could not boot into it, and the next daemon scan did not find it. Only the
// Hytale server can generate a world (chunk data, level metadata), and it does
// so on its own; TalePanel refuses to pretend otherwise. The create button has
// been removed from the web UI, and this endpoint stays only to give any old
// client a truthful answer instead of a fabricated success.
func (h *WorldHandler) CreateWorld(c *gin.Context) {
	c.JSON(http.StatusNotImplemented, gin.H{
		"error": "TalePanel cannot create Hytale worlds. Worlds are generated by the Hytale " +
			"server itself under universe/worlds and appear here automatically once the daemon " +
			"finds them on disk.",
	})
}

func (h *WorldHandler) SetActiveWorld(c *gin.Context) {
	serverID, ok := parseUUID(c, "id")
	if !ok {
		return
	}
	worldID, ok := parseUUID(c, "worldId")
	if !ok {
		return
	}
	if err := h.worldSvc.SetActiveWorld(c.Request.Context(), serverID, worldID); err != nil {
		switch {
		case errors.Is(err, services.ErrWorldNotFound):
			c.JSON(http.StatusNotFound, gin.H{"error": "world not found"})
		case errors.Is(err, services.ErrServerNotFound):
			c.JSON(http.StatusNotFound, gin.H{"error": "server not found"})
		case errors.Is(err, services.ErrUnsafeWorldName):
			c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		default:
			h.log.Error("failed to set active world", zap.Error(err))
			c.JSON(http.StatusInternalServerError, gin.H{"error": "could not set active world"})
		}
		return
	}
	// The daemon writes Defaults.World into config.json; Hytale reads it at
	// boot. Say that plainly instead of implying the running server switched.
	c.JSON(http.StatusOK, gin.H{
		"message":          "Active world updated. Restart the server to load it.",
		"restart_required": true,
	})
}

func (h *WorldHandler) DeleteWorld(c *gin.Context) {
	serverID, ok := parseUUID(c, "id")
	if !ok {
		return
	}
	worldID, ok := parseUUID(c, "worldId")
	if !ok {
		return
	}
	if err := h.worldSvc.DeleteWorld(c.Request.Context(), serverID, worldID); err != nil {
		switch {
		case errors.Is(err, services.ErrWorldNotFound):
			c.JSON(http.StatusNotFound, gin.H{"error": "world not found"})
		case errors.Is(err, services.ErrServerNotFound):
			c.JSON(http.StatusNotFound, gin.H{"error": "server not found"})
		case errors.Is(err, services.ErrWorldActive):
			c.JSON(http.StatusConflict, gin.H{"error": err.Error()})
		case errors.Is(err, services.ErrUnsafeWorldName):
			c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		default:
			h.log.Error("failed to delete world", zap.Error(err))
			c.JSON(http.StatusInternalServerError, gin.H{"error": "could not delete world"})
		}
		return
	}
	c.JSON(http.StatusOK, gin.H{"message": "World deleted from the panel and from disk."})
}
